// Auto-generated GPU lib_exec for core
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kRegisterTarget: {
      auto typed = task.template Cast<RegisterTargetTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed = task.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed = task.template Cast<PutBlobTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed = task.template Cast<GetBlobTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kRegisterTarget:
      task.template Cast<RegisterTargetTask>()->SerializeOut(archive);
      break;
    case Method::kGetOrCreateTag:
      task.template Cast<core::GetOrCreateTagTask<core::CreateParams>>()->SerializeOut(archive);
      break;
    case Method::kPutBlob:
      task.template Cast<PutBlobTask>()->SerializeOut(archive);
      break;
    case Method::kGetBlob:
      task.template Cast<GetBlobTask>()->SerializeOut(archive);
      break;
    default: break;
  }
}

static HSHM_GPU_FUN chi::gpu::TaskResume RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  switch (method) {
    case Method::kRegisterTarget:
      co_await self->RegisterTarget(task_ptr.template Cast<RegisterTargetTask>(), rctx);
      break;
    case Method::kGetOrCreateTag:
      co_await self->GetOrCreateTag(task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>(), rctx);
      break;
    case Method::kPutBlob:
      co_await self->PutBlob(task_ptr.template Cast<PutBlobTask>(), rctx);
      break;
    case Method::kGetBlob:
      co_await self->GetBlob(task_ptr.template Cast<GetBlobTask>(), rctx);
      break;
    default: break;
  }
  co_return;
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method, size_t stack_size) {
  auto *ipc = CHI_IPC;
  switch (method) {
    case Method::kRegisterTarget: {
      auto fp = ipc->template NewTaskExec<RegisterTargetTask>(stack_size);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(
          reinterpret_cast<char *>(fp.ptr_) + sizeof(RegisterTargetTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kGetOrCreateTag: {
      auto fp = ipc->template NewTaskExec<core::GetOrCreateTagTask<core::CreateParams>>(stack_size);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(
          reinterpret_cast<char *>(fp.ptr_) + sizeof(core::GetOrCreateTagTask<core::CreateParams>));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kPutBlob: {
      auto fp = ipc->template NewTaskExec<PutBlobTask>(stack_size);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(
          reinterpret_cast<char *>(fp.ptr_) + sizeof(PutBlobTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kGetBlob: {
      auto fp = ipc->template NewTaskExec<GetBlobTask>(stack_size);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(
          reinterpret_cast<char *>(fp.ptr_) + sizeof(GetBlobTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    default: return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  }
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::DefaultLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    size_t stack_size, chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = AllocTaskImpl(self_, method, stack_size);
  if (!block.task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, block.task_ptr);
  }
  return block;
}

static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void LoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultSaveArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuSaveTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kRegisterTarget:
      task.template Cast<RegisterTargetTask>().ptr_->~RegisterTargetTask();
      break;
    case Method::kGetOrCreateTag:
      task.template Cast<core::GetOrCreateTagTask<core::CreateParams>>().ptr_->~GetOrCreateTagTask();
      break;
    case Method::kPutBlob:
      task.template Cast<PutBlobTask>().ptr_->~PutBlobTask();
      break;
    case Method::kGetBlob:
      task.template Cast<GetBlobTask>().ptr_->~GetBlobTask();
      break;
    default: task.ptr_->~Task(); break;
  }
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_default_ = &AllocLoadTaskDefaultImpl;
  alloc_load_task_wrap_ = &AllocLoadTaskWrapImpl;
  load_task_default_ = &LoadTaskDefaultImpl;
  load_task_wrap_ = &LoadTaskWrapImpl;
  save_task_default_ = &SaveTaskDefaultImpl;
  save_task_wrap_ = &SaveTaskWrapImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
